### ISSUE TITLE
Feature request: blended frame removal with frame interpolation replacement.

### ISSUE THREAD

**Issue by adamcarter1** [Justin62628/Squirrel-RIFE#484]
Hi, amazing software.

i have many dvds of anime that were authored incorrectly when they were archived or created. 
despite originally created to be played at 23.976 or 24. Lots of my anime tv shows from the 80s especially if they were created from PAL masters of NTSC content, sometimes have crappy blended frames. A sorta half way in between frame of two adjacent frames. It looks like crap especially if upscale. 

i want to preserver the 23.976 frame rate. Would love the software to go thru the file recognize the frame as blended. 
remove it, and then use rife to create a proper non-blended frame. There is usually 1-3 blended frames per second.

i have tried using avisynth to remove them, but it can be hit or miss. 

Thank you for listening.

**Comment by Justin62628** [comment]
it'll be extremely hard to recognize blended frames I guess, since the information that could distinguish them has been permanently lost due to encoding. 
The only feasible way to solve this issue is to train a new AI that could pick blended frames out. However, this can also lead to false classification of real, un-blended frames since AI can never be accurate.
If you have any idea on recognizing blended frames please comment follow, thanks!

**Comment by Justin62628** [comment]
I'm closing this due to no further discussion present
